spring:
  application:
    name: map-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  level:
    root: INFO

  file:
    name: logs/maps.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: true

app:
  files:
    presign_minutes: 10

jwt:
  secret: ${JWT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
server:
  tomcat.mbeanregistry.enabled: true
